---
# defaults file for service_dpl2 

# Root is required for some plays in this role.  If root_access is 'no', then root-dependent plays will be skipped.
root_access: "yes"
# Number of hosts to process at simultaneously.  Leave undefined to set to unlimited.
dpl2_serial: ""
dpl2_location: "seattle" # "seattle" or ""
dpl2_prefix: "test"
dpl2_user: "root"
dpl2_version: "1.4.0"
dpl2_user_directory: "/opt/{{ dpl2_user }}"
dpl2_dockercomposeyml_path: "{{ dpl2_user_directory }}/dpl2_{{ dpl2_prefix }}"
dpl2_docker_version: "2"
dpl2_container_name: "dpl2_{{ dpl2_prefix }}"
dpl2_container_registry: "us.gcr.io/mshn-corp-154420/data-pipeline"
dpl2_image: "{{ dpl2_container_registry }}/cracker:{{ dpl2_version }}"
dpl2_volume_1: "./config:/opt/dpl2/config"
dpl2_volume_2: "{{ dpl2_config_data_file_path }}:{{ dpl2_config_data_file_path }}"
dpl2_volume_3: "/var/log/{{ dpl2_user }}:/var/log/{{ dpl2_user }}"
dpl2_ports: "80:8080"
dpl2_restart_state: "always"
dpl2_config_mode: "barrel"
dpl2_config_barrel_server: "1.2.3.4"
dpl2_config_barrel_server_port: "8701"
dpl2_config_datasource: "{{ dpl2_prefix }}" 
dpl2_config_data_file_path: "{{ dpl2_dockercomposeyml_path }}/datas_{{ dpl2_prefix }}"
### The 2 variables below need to be enclosed with single and double quotes to ensure they are written out as strings.
dpl2_config_read_mode: "'tail'" ###
dpl2_config_data_file_prefix: '"MIRROR-TEST"' 
###
dpl2_config_async_validation: "false"
dpl2_config_filename_validation: "true"
dpl2_config_send_kills: "true"
dpl2_config_logcount: "100000"
dpl2_config_logfile_path: "/var/log/{{ dpl2_user }}/dpl2_{{ dpl2_prefix }}.log"
dpl2_config_log_level: "4"

# Dpl2-specific variables for the SSHFS role:
sshfs_working_directory: "{{ dpl2_dockercomposeyml_path }}"
sshfs_user: "{{ dpl2_user }}"
sshfs_command_arguments: "-o IdentityFile={{ sshfs_key_path }}/{{ sshfs_key_name }} -o StrictHostKeyChecking=no -o reconnect -o allow_other -o cache=no -o Compression=no"
sshfs_mountpoint_directories:
    - "{{ dpl2_config_data_file_path }}"
    - "{{ dpl2_config_data_file_path }}_rsync"
sshfs_remote_host: "test"
sshfs_remote_path: "/test/data"
sshfs_key_path: "/home/{{ dpl2_user }}/.ssh"
sshfs_key_name: "{{ dpl2_prefix }}_key"
sshfs_key_config: |
    Host "{{ sshfs_remote_host }}"
      Hostname "{{ sshfs_remote_host }}"
      User "{{ dpl2_user }}"
      IdentityFile "{{ sshfs_key_path }}/{{ sshfs_key_name }}"
      Compression yes
      CompressionLevel 3
      ServerAliveInterval 30

# Dpl2-specific variables for the Prometheus Node Exporter roles:
prometheus_exporters_common_user: "{{ dpl2_user }}"
prometheus_exporters_common_group: "{{ dpl2_user }}"
prometheus_exporters_common_root_dir: "{{ dpl2_user_directory }}/prometheus/exporters"
prometheus_exporters_common_dist_dir: "{{ prometheus_exporters_common_root_dir }}/dist"
prometheus_exporters_common_log_dir: "/var/log/{{ dpl2_user }}/prometheus"

# Dpl2 global lists:
dpl2_global_whitelist: |
    "1",
    "2",
dpl2_blacklist: |
    "test", 
    "example", 
