---

- name: If the system service manager is 'sysvinit', ensure a sysvinit service unit exists.
  template:
    src: etc/init.d/prometheus-node-exporter.j2
    dest: /etc/init.d/prometheus-node-exporter
    owner: root
    group: root
    mode: 0755
  notify:
    - Restart node exporter.
