---

- name: Ensure logrotate is installed.
  when: logrotate_scripts is defined
  apt:
    name: logrotate
    state: present

- name: Ensure logrotate.d scripts exist.
  when: logrotate_scripts is defined
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}/{{ item.name }}"
    backup: no
    force: yes
    owner: root
    group: root
    mode: 0644
  with_items: "{{ logrotate_scripts }}"

- name: Ensure the logrotate cronjob is present to check if any logs exceed 'maxsize' or need to be rotated hourly.
  when: logrotate_scripts is defined
  cron:
    name: "Logrotate"
    special_time: "hourly"
    job: "logrotate /etc/logrotate.conf"
    state: present
