---

dpl1_prefix: "test2"
dpl1_ports_1: "7800:7800"
dpl1_ports_2: "9092:9090"
dpl1_bigtable_config_server_address: "0.0.0.0:4800"
dpl1_bigtable_config_mds_conn_string: "bigtable:///example-project/instance/example2?write_batch_limit=1000&num_channels=58"
