---

- name: Re-enable node exporter service.
  command: systemctl reenable prometheus-node-exporter.service

- name: Re-init node exporter.
  command: initctl reload-configuration

- name: Restart node exporter.
  service:
    name: prometheus-node-exporter
    state: restarted
