---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker-compose

- name: Ensure Ubuntu '18.04' apt dependencies are installed.
  when: ansible_distribution_version == '18.04'
  apt:
    name:
      - python3-pip
    state: present

- name: Ensure apt dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"

# The separate playbook below is required for Ubuntu <=14.04 and older Debian versions that do not support SNI for APT, which will cause the play above to fail.
- include_tasks: without-sni.yml
  when: add_repository_key is failed

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
